from __future__ import annotations

import argparse
from pathlib import Path

# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE


def run_make_agent(args: argparse.Namespace) -> None:
    """Generates a new AgentSpec file in the definitions directory."""
    name = args.name.lower().replace(" ", "_")
    description = (
        args.description or f"Assistant specialized in {name.replace('_', ' ')}"
    )
    role = args.role or f"Expert at {name.replace('_', ' ')}."
    backstory = args.backstory or (
        f"Created to handle {name.replace('_', ' ')} requests with consistency."
    )
    goals = args.goal or [
        f"Deliver accurate outputs for {name.replace('_', ' ')} tasks.",
        "Use available tools when they materially improve correctness.",
    ]
    boundary = args.boundary or "Avoid tasks outside of specialized domain."

    # Template for the new agent specification file
    file_content = f"""from agentic_system.agents.registry import AgentSpec

#================================================================
# AGENT CONFIGURATION GUIDE
#================================================================
# name:          Unique internal ID. Use snake_case.
#                Example: "customer_support_specialist"
#
# description:   High-level summary for the router/orchestrator.
#                Example: "Handles user billing inquiries and subscription changes."
#
# role:          The persona name or title.
#                Example: "Senior Billing Support Expert"
#
# backstory:     Narrative context to shape personality and expertise.
#                Example: "You have 15 years experience in fintech customer relations. 
#                You are polite, professional, and explain complex billing terms simply."
#
# goals:         List of specific objectives the agent must prioritize.
#                Example: ["Verify user identity", "Resolve billing disputes", "Suggest upgrades"]
#
# boundary:      Explicit constraints on scope.
#                Example: "Do not provide legal advice or authorize refunds over $50."
#
# system_prompt: Core behavioral logic and technical instructions for the LLM.
#                Example: "Always output results in JSON format. If you cannot help, 
#                escalate to human_agent immediately. Do not disclose internal API keys."
#
# tool_names:    List of specific tool IDs assigned to this agent.
#                Optional and additive with tool_groups.
#                Example: ["search_user_db", "process_payment", "send_email"]
#
# tool_groups:   List of predefined tool groups for batch access.
#                Optional and additive with tool_names.
#                Example: ["core", "finances", "notifications"]
#
# Note: These are Both tool_names and tool_groups are additive. To have NO tools, both must be empty [].
# ==================================================================================

agent = AgentSpec(
    name          = {name!r},
    description   = {description!r},
    role          = {role!r},
    backstory     = {backstory!r},
    goals         = {goals!r},
    boundary      = {boundary!r},
    system_prompt = (
        "You are a specialized assistant."
    ),
    tool_names    = [],
    tool_groups   = ["core"],
)
"""

    definitions_dir = Path(__file__).parent.parent / "agents" / "definitions"
    if not definitions_dir.exists():
        definitions_dir.mkdir(parents=True, exist_ok=True)
        (definitions_dir / "__init__.py").write_text("# Agent definitions package.\n")

    agent_file = definitions_dir / f"{name}.py"

    if agent_file.exists():
        print(f"Error: Agent file '{agent_file.name}' already exists.")
        return

    agent_file.write_text(file_content, encoding="utf-8")

    print(f"✅ Successfully created agent file: {name}.py")
    print(f"📍 Location: {agent_file}")
